# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-21 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0005_auto_20171117_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentchannel',
            name='chef_repo_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentchannel',
            name='spec_sheet_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
