# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-22 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0006_auto_20171120_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentchannel',
            old_name='qa_sheet_url',
            new_name='qa_sheet_id',
        ),
    ]
