# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-28 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0006_auto_20171120_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentchannel',
            name='new_run_complete',
            field=models.BooleanField(default=False),
        ),
    ]
