# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-30 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0007_contentchannel_new_run_complete'),
        ('runs', '0007_auto_20171122_0130'),
    ]

    operations = [
    ]
