# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-12 02:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0008_merge_20171130_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentchannel',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='saved_channels', to=settings.AUTH_USER_MODEL),
        ),
    ]
