# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-17 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0009_auto_20180111_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentchannel',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
